# These are supported funding model platforms

github: WhiteDevilSM # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
buy_me_a_coffee: Rolex901 # Replace with a single Buy Me a Coffee username
custom: Rolex901
 # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

